name: build-publish-release
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  armv7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Enable QEMU for multi-arch emulation
      - uses: docker/setup-qemu-action@v3

      # Enable Buildx (multi-arch builder)
      - uses: docker/setup-buildx-action@v3

      # Optional: cache deps
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
